chat/urls.py
<<<<<<< HEAD
from django.urls import path, re_path, include
from chat.views import (chat, new_message_check,
                        wink, chat_ajax, chat_home,
                        read_messages, winks,
                        read_wink, read_view,
                        views, reject,
                        block_user,unblock_user,
                        delete_conversation
                        )

urlpatterns = [
    path('<int:id>/', chat, name="chat"),
    path('home/', chat_home, name="chat_home"),
    path('ajax/winks/', wink, name="wink"),
    path('ajax/reject/', reject, name="reject"),
    path('block_user/<int:user_id>/', block_user, name='block_user'),
    path('unblock_user/<int:user_id>/', unblock_user, name='unblock_user'),
    path('ajax/new_message_check/', new_message_check, name='new_message_check'),
    path('ajax/read/', read_messages, name="read_messages"),
    path('ajax/new_message/', chat_ajax, name="new_message"),
    path('winks/', winks, name="winks"),
    path('views/', views, name="views"),
    path('ajax/read-view/', read_view, name='read_view'),
    path('ajax/read-wink/', read_wink, name='read_wink'),
    path('delete_conversation/<int:conversation_id>/', delete_conversation, name='delete_conversation'),
]

# For the commented section, you can update it similarly:

# from profiles.views import index, logout, login, register, user_profile, create_profile, validate_username
# from profiles import url_reset

# urlpatterns += [
#     path('cart/', view_cart, name="view_cart"),
#     path('cart/add/<int:id>/', add_to_cart, name="add_to_cart"),
#     path('cart/adjust/<int:id>/', adjust_cart, name="adjust_cart"),
# ]
=======
from django.conf.urls import url, include
from chat.views import chat, create, new_message_check, wink, chat_ajax, chat_home, read_messages, winks, read_wink, read_view, views

urlpatterns = [
    url(r'^(?P<id>\d+)', chat, name="chat"),
    url(r'^home/', chat_home, name="chat_home"),
    url(r'^ajax/winks/$', wink, name="wink"),
    url(r'^ajax/new_message_check/$', new_message_check, name='new_message_check'),
    url(r'^ajax/read/$', read_messages, name="read_messages"),
    url(r'^ajax/new_message/$', chat_ajax, name="new_message"),
    url(r'^winks/$', winks, name="winks"),
    url(r'^views/$', views, name="views"),
    url(r'^ajax/read-view/', read_view),
    url(r'^ajax/read-wink/', read_wink),
    url(r'^$', create, name="create"),
]


# from django.conf.urls import url, include
# from profiles.views import index, logout, login, register, user_profile, create_profile, validate_username
# from profiles import url_reset


# urlpatterns = [
#     url(r'^$', view_cart, name="view_cart"),
#     url(r'^add/(?P<id>\d+)', add_to_cart, name="add_to_cart"),
#     url(r'^adjust/(?P<id>\d+)', adjust_cart, name="adjust_cart")
#     ]
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)

dating_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('profiles.urls')),
    path('chat/', include('chat.urls')),
    path('Admin/urls/',include('Custom_admin.urls')),
    path('subscribe/', include('checkout.urls')),
    path('my-account/', include('account.urls')),
    path('search/', include('search.urls')),
    path('Password/reset/', include('pass.urls')),
    #path('payments/', include('django_pesapal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
=======
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from profiles import urls as profile_urls
from chat import urls as chat_urls
from home import urls as home_urls
from account import urls as account_urls
from checkout import urls as subscribe_urls
from search import urls as search_urls
from django.views.static import serve
from .settings import MEDIA_ROOT


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(home_urls)),
    url(r'accounts/', include(profile_urls)),
    url(r'chat/', include(chat_urls)),
    url(r'subscribe/', include(subscribe_urls)),
    url(r'my-account/', include(account_urls)),
    url(r'search/', include(search_urls)),
    url(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}) 
    ]
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)

profiles/urls.py
<<<<<<< HEAD
from django.urls import path, re_path, include
from profiles.views import logout, login, register, create_profile, member_profile, delete, verification_message
from profiles import url_reset
from . import views

urlpatterns = [
    path('logout/', logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('register/', register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('create-profile/', create_profile, name='create_profile'),
    path('delete/', delete, name="delete"),
    path('verification-message/', verification_message, name="verification_message"),
    path('member/<int:id>/', member_profile, name='member_profile'),
    path('password-reset/', include(url_reset)),
    path('user/after/',views.after_login,name='after_login'),
]
=======
from django.conf.urls import url, include
from profiles.views import logout, login, register, user_profile, create_profile, validate_username, member_profile
from profiles import url_reset

urlpatterns = [
    url(r'^logout/', logout, name='logout'),
    url(r'^login/', login, name='login'), 
    url(r'^register/', register, name='register'),
    url(r'^create-profile/', create_profile, name='create_profile'),
    url(r'^edit/', user_profile, name="user_profile"),
    url(r'^member/(?P<id>\d+)', member_profile, name='member_profile'),
    url(r'^ajax/validate_username/$', validate_username, name='validate_username'),
    url(r'^password-reset/', include(url_reset))
]
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
<<<<<<< HEAD
from chat.models import ChatSession
from checkout.models import Subscription
from django.db.models.signals import post_save, pre_delete
=======
from django.db.models.signals import post_save
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
from django.utils.crypto import get_random_string
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid
import datetime
import os
import math
from django.db.models.expressions import RawSQL
<<<<<<< HEAD
import stripe
from django.db.backends.signals import connection_created
from django.dispatch import receiver
import os


"""
Only necessary for local and testing sqlite databases
As SQLite does not support math functions, the following function adds the
capability for it to do so
"""
if "DEVELOPMENT" in os.environ or "TESTING" in os.environ:
    @receiver(connection_created)
    def extend_sqlite(connection=None, **kwargs):
        cf = connection.connection.create_function
        cf('acos', 1, math.acos)
        cf('cos', 1, math.cos)
        cf('radians', 1, math.radians)
        cf('sin', 1, math.sin)

class LocationManager(models.Manager):
    
    # Assistance from https://stackoverflow.com/questions/19703975/django-sort-by-distance
    def nearby_locations(self, citylat, citylong, max_distance=None):
=======
import math
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def extend_sqlite(connection=None, **kwargs):
    # sqlite doesn't natively support math functions, so add them
    cf = connection.connection.create_function
    cf('acos', 1, math.acos)
    cf('cos', 1, math.cos)
    cf('radians', 1, math.radians)
    cf('sin', 1, math.sin)

class LocationManager(models.Manager):
    # def nearby_locations(self, cityLat, cityLong, radius=100, use_miles=True):
    #     # if use_miles:
    #     #     distance_unit = 3959
    #     # else:
    #     distance_unit = 6371
        
    #     from django.db import connection, transaction
    #     from django.conf import settings
    #     cursor = connection.cursor()
    #     # As certain math functions not usable in sqlite, this check is used to make them available
    #     # Uses Haversine formula to determine radius to check for close values
    #     # Assistance from https://stackoverflow.com/questions/1916953/filter-zipcodes-by-proximity-in-django-with-the-spherical-law-of-cosines
    #     if settings.DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    #         connection.connection.create_function('acos', 1, math.acos)
    #         connection.connection.create_function('cos', 1, math.cos)
    #         connection.connection.create_function('radians', 1, math.radians)
    #         connection.connection.create_function('sin', 1, math.sin)
        
    #     sql = """SELECT id, (acos(sin(radians(%f)) * sin(radians(cityLat)) + cos(radians(%f))
    #       * cos(radians(cityLat)) * cos(radians(%f-cityLong))) * %d)
    #     AS distance FROM profiles_profile WHERE distance < %f
    #     ORDER BY distance;""" % (cityLat, cityLat, cityLong, distance_unit, radius)
    #     cursor.execute(sql)
    #     ids = [row[0] for row in cursor.fetchall()]
        
    #     return self.filter(id__in=ids)
    
    # Assistance from https://stackoverflow.com/questions/19703975/django-sort-by-distance
    def nearby_locations(self, cityLat, cityLong, max_distance=None):
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
        """
        Return objects sorted by distance to specified coordinates
        which distance is less than max_distance given in kilometers
        """
        gcd_formula = "6371 * acos(cos(radians(%s)) * \
<<<<<<< HEAD
        cos(radians(citylat)) \
        * cos(radians(citylong) - radians(%s)) + \
        sin(radians(%s)) * sin(radians(citylat)))"
        distance_raw_sql = RawSQL(
            gcd_formula,
            (citylat, citylong, citylat)
        )
    
=======
        cos(radians(cityLat)) \
        * cos(radians(cityLong) - radians(%s)) + \
        sin(radians(%s)) * sin(radians(cityLat)))"
        distance_raw_sql = RawSQL(
            gcd_formula,
            (cityLat, cityLong, cityLat)
        )
    
        # qs = Profile.objects.all().annotate(distance=distance_raw_sql).order_by('distance')
        # Better way for this?
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
        if max_distance is not None:
            return self.annotate(distance=distance_raw_sql).filter(distance__lt=max_distance)
        else:
            return self.annotate(distance=distance_raw_sql)

<<<<<<< HEAD
class custom_admin(models.Model):
    """Passing Custom Admin Attributes"""
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    email=models.EmailField(unique=True)
    pic= models.ImageField(upload_to='admin_pic',blank=True)

    def __str__(self):
        return self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name = 'profile_detail')
    email = models.EmailField(unique=True,null=True)
=======

# def get_locations_nearby_coords(self, cityLat, cityLong, max_distance=None):
#         """
#         Return objects sorted by distance to specified coordinates
#         which distance is less than max_distance given in kilometers
#         """
        
        
#         gcd_formula = "6371 * acos(cos(radians(%s)) * \
#         cos(radians(cityLat)) \
#         * cos(radians(cityLong) - radians(%s)) + \
#         sin(radians(%s)) * sin(radians(cityLat)))"
#         distance_raw_sql = RawSQL(
#             gcd_formula,
#             (cityLat, cityLong, cityLat)
#         )
#         qs = Profile.objects.all().annotate(distance=distance_raw_sql).order_by('distance')
#         if max_distance is not None:
#             qs = qs.filter(distance__lt=max_distance)
#         return qs

class Profile(models.Model):
    # Limit username 11 chars
    user = models.OneToOneField(User, on_delete=models.CASCADE)
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
    bio = models.TextField(max_length=500, default='', blank=False)
    HAIR_COLOUR = (
        ('BLACK', 'Black'),
        ('BLONDE', 'Blonde'),
        ('BROWN', 'Brown'),
        ('RED', 'Red'),
        ('GREY', 'Grey'),
        ('BALD', 'Bald'),
        ('BLUE', 'Blue'),
        ('PINK', 'Pink'),
        ('GREEN', 'Green'),
        ('PURPLE', 'Purple'),
        ('OTHER', 'Other'),
    )
    BODY_TYPE = (
        ('THIN', 'Thin'),
        ('AVERAGE', 'Average'),
        ('FIT', 'Fit'),
        ('MUSCULAR', 'Muscular'),
        ('A LITTLE EXTRA', 'A Little Extra'),
        ('CURVY', 'Curvy'),
    )
    LOOKING_FOR = (
        ('MALE', 'Men'),
        ('FEMALE', 'Women'),
        ('BOTH', 'Both'),
    )
<<<<<<< HEAD

=======
    APPROVAL = (
        ('TO BE APPROVED', 'To be approved'),
        ('APPROVED', 'Approved'),
        ('NOT APPROVED', 'Not approved')
    )
    
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
    HAIR_LENGTH = (
        ('LONG', 'Long'),
        ('SHOULDER LENGTH', 'Shoulder Length'),
        ('AVERAGE', 'Average'),
        ('SHORT', 'Short'),
        ('SHAVED', 'Shaved')
    )
    ETHNICITY = (
        ('WHITE', 'White'),
        ('ASIAN: INDIAN', 'Asian: Indian'),
        ('ASIAN: PAKISTANI', 'Asian: Pakistani'),
        ('ASIAN: BANGLADESHI', 'Asian: Bangladeshi'),
        ('ASIAN: CHINESE', 'Asian: Chinese'),
        ('BLACK', 'Black'),
        ('MIXED', 'Mixed'),
        ('OTHER ETHNICITY', 'Other Ethnicity')
    )
    RELATIONSHIP_STATUS = (
        ('NEVER MARRIED', 'Never Married'),
        ('DIVORCED', 'Divorced'),
        ('WIDOWED', 'Widowed'),
        ('SEPARATED', 'Separated')
    )
    EDUCATION = (
    ('HIGH SCHOOL', 'High School'),
    ('COLLEGE', 'College'),
    ('BACHELORS DEGREE', 'Bachelors Degree'),
    ('MASTERS', 'Masters'),
    ('PHD / POST DOCTORAL', 'PhD / Post Doctoral'),
    )
    GENDER = (
        ("MALE", "Male"),
        ("FEMALE", "Female"))
<<<<<<< HEAD

    gender = models.CharField(choices=GENDER, default="MALE", max_length=6)
    hair_length = models.CharField(choices=HAIR_LENGTH, default="LONG", blank=False, max_length=100)
    ethnicity = models.CharField(choices=ETHNICITY, default="BLACK", blank=False, max_length=100)
    relationship_status = models.CharField(choices=RELATIONSHIP_STATUS, default="NEVER MARRIED", blank=False, max_length=100)
    education = models.CharField(choices=EDUCATION, default="HIGH SCHOOL", blank=False, max_length=100)
    height = models.DecimalField(max_digits=10, default=180.34, decimal_places=2)
=======
    
    gender = models.CharField(choices=GENDER, default="MALE", max_length=6)
    hair_length = models.CharField(choices=HAIR_LENGTH, default="LONG", blank=False, max_length=100)
    ethnicity = models.CharField(choices=ETHNICITY, default="WHITE", blank=False, max_length=100)
    relationship_status = models.CharField(choices=RELATIONSHIP_STATUS, default="NEVER MARRIED", blank=False, max_length=100)
    education = models.CharField(choices=EDUCATION, default="HIGH SCHOOL", blank=False, max_length=100)
    height = models.DecimalField(max_digits=10, default=100, decimal_places=2)
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
    hair_colour = models.CharField(choices=HAIR_COLOUR, default="BLACK", blank=False, max_length=10)
    body_type = models.CharField(choices=BODY_TYPE, default="AVERAGE", blank=False, max_length=15)
    looking_for = models.CharField(choices=LOOKING_FOR, default='BOTH', blank=False, max_length=6)
    children = models.BooleanField(default=False)
    location = models.CharField(max_length=100, default='', blank=False)
<<<<<<< HEAD
    citylat = models.DecimalField(max_digits=9, decimal_places=6, default='-2.0180319')
    citylong = models.DecimalField(max_digits=9, decimal_places=6, default='52.5525525')
    birth_date = models.DateField(null=True, default='1990-01-01', blank=True)

profiles/templates/account_activation_email.html
Hi {{user.username}}Please  click the email link below to verify your email and complete your registration:
http://{{domain}}{% url 'activate' uidb64=uid token=token %}

profiles/templates/create-profile.html
<<<<<<< HEAD
{% extends 'base.html' %} {% block page_title %}Update your Profile{% endblock %} {% load static from static %} 
<!--CSS for datepicker-->
{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
{% endblock %} 

{% block content %}
<!--Profile details form-->
<section class="profile-card-container">
 {%if messages%}
   {%for message in messages%}
   <p class="text-info">{{message}}</p>
   {%endfor%}
 {%endif%}

    <div class="card-container card-margin-top">
        <div class="card-form card">
            <div class="card-form-container">
                <h3>Profile Details</h3>
                <hr>
                <p class="card-form-subtitle">Customise your public profile</p>
                <p class="card-form-description">This is your opportunity to let your personality shine. A well crafted profile can increase your engagement 4x so try to make it an honest expression of who you are!</p>
                <form class="create-profile-form standard-form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %} {{ profile_form }}
                    <!--Profile photos form-->
                    <label>Profile Photos: </label> {{ formset.management_form }}
                    <div class="profile-form-container">
                        {% for form in formset %}
                        <div id="field_{{form.id.id_for_label}}" class="profile-photo-container">

                            <div {% if not form.initial.image %}style="display: none;" {% endif %} class="profile-delete-icon-container">
                                <i onclick="delete_profile_photo( event, 'field_{{form.id.id_for_label}}' )" class="far fa-trash-alt"></i>
                            </div>
                            {{form}}
                            <div class="profile-photo-overlay">
                                <div class="profile-icon-container-absolute">
                                    <div class="profile-icon-container-flex">
                                        <i class="fas fa-plus"></i>
                                    </div>
                                </div>
                                {% if form.initial.image %}
                                <div class="profile-photo-image" style="background-image: url({{form.initial.image.url}})"></div>
                                {% else %}
                                <div class="profile-photo-image" style="background-image: none"></div>
                                {% endif %}
                            </div>

                            {% for hidden in form %} {% if not 'image' in hidden.auto_id %}
                            <input hidden class="delete-hidden-input" type="checkbox" name="delete" value="{{ hidden.value }}"> {% endif %} {% endfor %}

                        </div>
                        {% endfor %}
                    </div>
                    <div class="standard-form-submit">
                        <input type="submit" value="UPDATE" class="submit-wide submit-success" name="message_submit">
                        <img class="loading-image" src="{% static 'temp/34-1.gif' %}"></img>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %} {% block js %}
<script>
    // Using Google Places API, display autocomplete options for location
    // Assistance from Google Maps API documentation
    var placeSearch, autocomplete;
    function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(
            (document.getElementById('autocomplete')), { types: ['geocode'] })  
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            // Update hidden fields with selected location and coordinates
            document.getElementById('autocomplete').value = place.name;
            document.getElementById('id_citylat').value = place.geometry.location.lat().toFixed(6);
            document.getElementById('id_citylong').value = place.geometry.location.lng().toFixed(6);
        })  
    }
</script>
<!--Google maps and datepicker dependencies-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8CKdpcMMIDq0BZ7x7DMbH_71XpVH4HWo&libraries=places&callback=initAutocomplete" async defer></script>

=======


{% extends 'base.html' %} {% block page_title %}Create Profile{% endblock %} {% block page_heading %}Create Profile{% endblock %} 
{% block css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
{% endblock %}
{% block content %}

<section class="profile-card-container">
  <div class="card-container card-margin-top">
    <div class="card-form card">
      <div class="card-form-container">
        <h3>Profile Details</h3>
        <hr>
        <p class="card-form-subtitle">Customise your public profile</p>
        <p class="card-form-description">This is your opportunity to let your personality shine. A well crafted profile can increase your engagement 4x so try to make it an honest expression of who you are!</p>
        <form class="create-profile-form standard-form" method="POST" enctype="multipart/form-data">
          <!--https://docs.djangoproject.com/en/1.9/topics/forms/#s-looping-over-the-form-s-fields-->
          {% csrf_token %} {{ profile_form }}
          <!--{{ image_form }}-->
          <label>Profile Photos: </label> {{ formset.management_form }}
          <div class="profile-form-container">
            {% for form in formset %}
            <div id="field_{{form.id.id_for_label}}" class="profile-photo-container">
              
              <div {% if not form.initial.image %}style="display: none;"{% endif %} class="profile-delete-icon-container">
                <i onclick="delete_profile_photo( event, 'field_{{form.id.id_for_label}}' )" class="far fa-trash-alt"></i>
              </div>
              {{form}}
              <div class="profile-photo-overlay">
                <div class="profile-icon-container-absolute">
                  <div class="profile-icon-container-flex">
                    <i class="fas fa-plus"></i>
                  </div>
                </div>
                {% if form.initial.image %}
                <div class="profile-photo-image" style="background-image: url({{form.initial.image.url}})"></div>
                {% else %}
                <div class="profile-photo-image" style="background-image: none"></div>
                {% endif %}
              </div>
              
              {% for hidden in form %}
              {% if not 'image' in hidden.auto_id %}
              <input hidden class="delete-hidden-input" type="checkbox" name="delete" value="{{ hidden.value }}">
              {% endif %}
              {% endfor %}
              
            </div>
            {% endfor %}
          </div>

          <input type="submit" value="UPDATE" class="submit-wide submit-success" name="message_submit">

        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %} {% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
<script>
// http://jsfiddle.net/LvsYc/
  function readURL(input) {
    
      var image_input_id = $(input).attr('id')
      
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#" + image_input_id).parent().find('.profile-delete-icon-container').css('display', 'inherit')
                $("#" + image_input_id).parent().find('.delete-hidden-input').attr('checked', false)
                $("#" + image_input_id).parent().find('.profile-photo-image').css('background-image', 'url("' + e.target.result + '")');
            }
            $(image_input_id).siblings('.profile-delete-icon-container').css("display","block")
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $(".profile-photo-input").change(function(){
        readURL(this);
    });


    function delete_profile_photo(event, field_id) {
      if ($(event.target).attr("class") == "far fa-trash-alt") {
        $("#" + field_id).find('.profile-photo-image').css('background','none')
        $("#" + field_id).find('.profile-photo-image').css('background-size','cover')
        $("#" + field_id).find('.profile-photo-input').val('')
        $("#" + field_id).find('.delete-hidden-input').attr('checked', true)
        $(event.target).parent().css("display","none")
      }
    }
    
    
    
  // Change to jQuery!
  var placeSearch, autocomplete;
  // This example displays an address form, using the autocomplete feature
  // of the Google Places API to help users fill in the information.
  function initAutocomplete() {
    // Create the autocomplete object, restricting the search to geographical
    // location types.
    autocomplete = new google.maps.places.Autocomplete(
      (document.getElementById('autocomplete')), { types: ['geocode'] });

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      var place = autocomplete.getPlace();
      document.getElementById('autocomplete').value = place.name;
      document.getElementById('id_cityLat').value = place.geometry.location.lat().toFixed(6);
      document.getElementById('id_cityLong').value = place.geometry.location.lng().toFixed(6);
    });

  }


  // Bias the autocomplete object to the user's geographical location,
  // as supplied by the browser's 'navigator.geolocation' object.
  function geolocate() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var geolocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        var circle = new google.maps.Circle({ center: geolocation, radius: position.coords.accuracy });
        autocomplete.setBounds(circle.getBounds());
      });
    }
  }

  $(function() {

    var min_date = new Date();
    min_date.setFullYear(min_date.getFullYear() - 18);
    
    $("#id_birth_date").datepicker({
      'endDate': min_date,
    });
  });
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8CKdpcMMIDq0BZ7x7DMbH_71XpVH4HWo&libraries=places&callback=initAutocomplete" async defer></script>
>>>>>>> 4efebe4 (Switch from C9 to AWS C9)
{% endblock %}

profiles/templates/profile.html
{% extends 'base.html' %}
{% block page_title %}Profile{% endblock %}
{% block page_heading %}{{user}}'s Profile{% endblock %}

{% block content %}
<p>{{profile.email}}</p>
{% for image in profile.profileimage_set.all %}
<img src="/media/{{image.image}}">
{% endfor %}
<p>{{user.profile.bio}}</p>
<p>{{user.profile.location}}</p>
<!--Add error message if incorrect location is added, saying users cannot find you-->
<p>{{user.profile.birth_date}}</p>
{% endblock %}

profiles/templates/verification-message.html
{% extends 'base.html' %} {% block page_title %}Verification Message{% endblock %}{% block content %}


<!--Verification information card-->
<section class="profile-card-container">
    <div class="card-container card-margin-top">
        <div class="card-form card">
            <div class="card-form-container">
                <h3>Verification</h3>
                <hr>
                <p>To ensure our dating community is safe and fun for all, every profile is manually verified by our verification team.
                    <br><br> Please bear with us while we approve your profile. During this time, you will still be able to use the site, however some features may be limited.
                    <br><br> Average approval time is 20 minutes<br><br></p>

                <a class="btn standard-button" href="{% url 'index' %}">START DATING</a>


            </div>

        </div>
    </div>
</section>

{% endblock %}